# AI4Privacy label mapping for bank PII use case
# Maps extensive PII entities to unified schema

O: O

# Personal names
B-PREFIX: B-PER
I-PREFIX: I-PER
B-FIRSTNAME: B-PER
I-FIRSTNAME: I-PER
B-MIDDLENAME: B-PER
I-MIDDLENAME: I-PER
B-LASTNAME: B-PER
I-LASTNAME: I-PER
B-NAME: B-PER
I-NAME: I-PER

# Organizations
B-COMPANY_NAME: B-ORG
I-COMPANY_NAME: I-ORG
B-COMPANYNAME: B-ORG
I-COMPANYNAME: I-ORG

# Locations - all map to ADDR for bank PII
B-CITY: B-ADDR
I-CITY: I-ADDR
B-STATE: B-ADDR
I-STATE: I-ADDR
B-COUNTRY: B-ADDR
I-COUNTRY: I-ADDR
B-STREET: B-ADDR
I-STREET: I-ADDR
B-BUILDINGNUMBER: B-ADDR
I-BUILDINGNUMBER: I-ADDR
B-ZIPCODE: B-ADDR
I-ZIPCODE: I-ADDR
B-SECONDARYADDRESS: B-ADDR
I-SECONDARYADDRESS: I-ADDR

# Financial
B-CREDITCARDNUMBER: B-CARD
I-CREDITCARDNUMBER: I-CARD
B-CREDITCARDCVV: B-CARD
I-CREDITCARDCVV: I-CARD
B-CREDITCARDISSUER: B-ORG
I-CREDITCARDISSUER: I-ORG
B-ACCOUNTNUMBER: B-BANK
I-ACCOUNTNUMBER: I-BANK
B-IBAN: B-BANK
I-IBAN: I-BANK
B-BIC: B-BANK
I-BIC: I-BANK
B-AMOUNT: B-MONEY
I-AMOUNT: I-MONEY
B-CURRENCY: B-MONEY
I-CURRENCY: I-MONEY

# Contact info
B-EMAIL: B-EMAIL
I-EMAIL: I-EMAIL
B-PHONEIMEI: B-PHONE
I-PHONEIMEI: I-PHONE
B-PHONENUMBER: B-PHONE
I-PHONENUMBER: I-PHONE

# IDs
B-SSN: B-SSN
I-SSN: I-SSN
B-DRIVERLICENSE: B-LICENSE
I-DRIVERLICENSE: I-LICENSE
B-PASSPORT: B-PASSPORT
I-PASSPORT: I-PASSPORT
B-IDCARD: B-MISC
I-IDCARD: I-MISC
B-VEHICLEIDENTIFICATIONNUMBER: B-MISC
I-VEHICLEIDENTIFICATIONNUMBER: I-MISC
B-VEHICLEREGISTRATION: B-MISC
I-VEHICLEREGISTRATION: I-MISC

# Dates and times
B-DATE: B-DATE
I-DATE: I-DATE
B-TIME: B-TIME
I-TIME: I-TIME
B-DOB: B-DATE
I-DOB: I-DATE
B-AGE: B-MISC
I-AGE: I-MISC

# Medical
B-MEDICALLICENSE: B-LICENSE
I-MEDICALLICENSE: I-LICENSE
B-ACCOUNTNAME: B-PER
I-ACCOUNTNAME: I-PER

# Other
B-USERNAME: B-MISC
I-USERNAME: I-MISC
B-PASSWORD: B-MISC
I-PASSWORD: I-MISC
B-IP: B-MISC
I-IP: I-MISC
B-IPV4: B-MISC
I-IPV4: I-MISC
B-IPV6: B-MISC
I-IPV6: I-MISC
B-MAC: B-MISC
I-MAC: I-MISC
B-URL: B-MISC
I-URL: I-MISC
B-JOBAREA: B-MISC
I-JOBAREA: I-MISC
B-JOBTITLE: B-MISC
I-JOBTITLE: I-MISC
B-JOBDESCRIPTOR: B-MISC
I-JOBDESCRIPTOR: I-MISC
B-GENDER: B-MISC
I-GENDER: I-MISC
B-SEX: B-MISC
I-SEX: I-MISC
B-USERAGENT: B-MISC
I-USERAGENT: I-MISC
B-MASKEDNUMBER: B-MISC
I-MASKEDNUMBER: I-MISC
B-PIN: B-MISC
I-PIN: I-MISC