# Gretel PII label mapping for bank use case
# Maps various PII entities to unified schema

O: O

# Personal identifiers
B-PERSON: B-PER
I-PERSON: I-PER
B-NAME: B-PER
I-NAME: I-PER

# Financial
B-CREDIT_CARD: B-CARD
I-CREDIT_CARD: I-CARD
B-BANK_ACCOUNT: B-BANK
I-BANK_ACCOUNT: I-BANK
B-IBAN: B-BANK
I-IBAN: I-BANK
B-SWIFT: B-BANK
I-SWIFT: I-BANK
B-ROUTING_NUMBER: B-BANK
I-ROUTING_NUMBER: I-BANK
B-ACCOUNT_NUMBER: B-BANK
I-ACCOUNT_NUMBER: I-BANK

# Government IDs
B-SSN: B-SSN
I-SSN: I-SSN
B-PASSPORT: B-PASSPORT
I-PASSPORT: I-PASSPORT
B-LICENSE: B-LICENSE
I-LICENSE: I-LICENSE
B-DRIVER_LICENSE: B-LICENSE
I-DRIVER_LICENSE: I-LICENSE

# Contact
B-PHONE: B-PHONE
I-PHONE: I-PHONE
B-EMAIL: B-EMAIL
I-EMAIL: I-EMAIL
B-ADDRESS: B-ADDR
I-ADDRESS: I-ADDR

# Locations -> ADDR for bank PII
B-CITY: B-ADDR
I-CITY: I-ADDR
B-STATE: B-ADDR
I-STATE: I-ADDR
B-COUNTRY: B-ADDR
I-COUNTRY: I-ADDR
B-ZIPCODE: B-ADDR
I-ZIPCODE: I-ADDR

# Dates and numbers
B-DATE: B-DATE
I-DATE: I-DATE
B-DOB: B-DATE  # Date of birth -> DATE
I-DOB: I-DATE
B-DATE_OF_BIRTH: B-DATE
I-DATE_OF_BIRTH: I-DATE

# Organizations
B-COMPANY: B-ORG
I-COMPANY: I-ORG
B-ORGANIZATION: B-ORG
I-ORGANIZATION: I-ORG

# Monetary values
B-AMOUNT: B-MONEY
I-AMOUNT: I-MONEY
B-CURRENCY: B-MONEY
I-CURRENCY: I-MONEY

# Generic PII
B-PII: B-MISC
I-PII: I-MISC
B-USERNAME: B-MISC
I-USERNAME: I-MISC
B-PASSWORD: B-MISC
I-PASSWORD: I-MISC
B-IP_ADDRESS: B-MISC
I-IP_ADDRESS: I-MISC