name: mistral-ner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # PyTorch packages with CUDA 12.1 support
    - --index-url https://download.pytorch.org/whl/cu121
    - torch>=2.7.0
    - torchvision>=0.22.0
    - torchaudio>=2.7.0
    # Core ML dependencies
    - accelerate>=1.7.0
    - datasets>=3.6.0
    - evaluate>=0.4.3
    - numpy>=2.2.5
    - protobuf>=6.31.0
    - peft>=0.4.0
    - sentencepiece>=0.2.0
    - seqeval>=1.2.2
    - transformers>=4.51.3
    - bitsandbytes>=0.41.0
    # Experiment tracking and visualization
    - wandb>=0.16.0
    - matplotlib>=3.10.3
    - seaborn>=0.13.2
    # Configuration and utilities
    - pyyaml>=6.0
    - python-dotenv>=1.0.0
    # Hyperparameter optimization
    - ray[tune]>=2.46.0
    - optuna>=4.3.0